---
title: "00-import"
title-block-banner: true
author:
  - name: Jinlong Ru
    orcid: 0000-0002-6757-6018
    email: jinlong.ru@gmail.com
    affiliations:
      - name: Institute of Virology, Helmholtz Centre Munich – German Research Center for Environmental Health, 85764 Neuherberg, Germany
      - neme: Chair of Prevention of Microbial Diseases, School of Life Sciences Weihenstephan, Technical University of Munich, 85354 Freising, Germany
date: 2022-11-06
toc: true
format: gfm
params:
  name: "00-import" # change if you rename file
---

```{r setup, message=FALSE, include=F}
# uuid::UUIDgenerate()
here::i_am(paste0(params$name, ".qmd"), uuid = "b3212655-a048-4ba9-8a9d-ad8bad8598f9")
projthis::proj_create_dir_target(params$name, clean = F)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
```

## Tasks

```{r}
library(conflicted)
library(here)
```


## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```
